[2024-10-24T18:18:47.011+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-24T18:18:47.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-23T01:00:00+00:00 [queued]>
[2024-10-24T18:18:47.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-23T01:00:00+00:00 [queued]>
[2024-10-24T18:18:47.064+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-10-24T18:18:47.081+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2024-10-23 01:00:00+00:00
[2024-10-24T18:18:47.098+0000] {standard_task_runner.py:64} INFO - Started process 640 to run task
[2024-10-24T18:18:47.103+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Nikita_Lapshin_experiment', 'train_and_log_model', 'scheduled__2024-10-23T01:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/HW2.py', '--cfg-path', '/tmp/tmpjfwmsmyd']
[2024-10-24T18:18:47.107+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask train_and_log_model
[2024-10-24T18:18:47.170+0000] {task_command.py:426} INFO - Running <TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-23T01:00:00+00:00 [running]> on host 701639cb5e9f
[2024-10-24T18:18:47.259+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lapshin Nikita' AIRFLOW_CTX_DAG_ID='Nikita_Lapshin_experiment' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T01:00:00+00:00'
[2024-10-24T18:18:47.260+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-24T18:18:47.277+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-2 with path datasets/prepared_data.csv
[2024-10-24T18:18:47.285+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-24T18:18:47.287+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-24T18:18:53.590+0000] {logging_mixin.py:188} INFO - result1
[2024-10-24T18:18:53.657+0000] {logging_mixin.py:188} WARNING - 2024/10/24 18:18:53 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-24T18:19:10.722+0000] {logging_mixin.py:188} INFO - result2 random_forest
[2024-10-24T18:19:17.115+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-10-24T18:27:12.636+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:27:14.347+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:27:14.919+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:27:16.147+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:27:19.450+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:28:17.312+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:28:19.229+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:28:19.646+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:28:20.239+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:28:25.131+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:28:25.720+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-24T18:28:27.091+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-24T18:28:28.188+0000] {logging_mixin.py:188} WARNING - 2024/10/24 18:28:28 INFO mlflow.models.evaluation.default_evaluator: Computing model predictions.
[2024-10-24T18:28:28.864+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/metrics/_regression.py:492 FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
[2024-10-24T18:28:28.875+0000] {logging_mixin.py:188} WARNING - 2024/10/24 18:28:28 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...
[2024-10-24T18:28:28.883+0000] {logging_mixin.py:188} WARNING - 2024/10/24 18:28:28 WARNING mlflow.models.evaluation.default_evaluator: SHAP or matplotlib package is not installed, so model explainability insights will not be logged.
[2024-10-24T18:36:40.710+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-10-24T18:36:41.976+0000] {process_utils.py:132} INFO - Sending 15 to group 640. PIDs of all processes in the group: [640]
[2024-10-24T18:36:42.020+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 640
[2024-10-24T18:36:42.269+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
