[2024-10-24T20:45:44.263+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-24T20:45:44.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lapshin_nikita_linear_regression.train_model manual__2024-10-24T20:45:11.903795+00:00 [queued]>
[2024-10-24T20:45:44.283+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lapshin_nikita_linear_regression.train_model manual__2024-10-24T20:45:11.903795+00:00 [queued]>
[2024-10-24T20:45:44.283+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-10-24T20:45:44.293+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-10-24 20:45:11.903795+00:00
[2024-10-24T20:45:44.328+0000] {standard_task_runner.py:64} INFO - Started process 2031 to run task
[2024-10-24T20:45:44.337+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lapshin_nikita_linear_regression', 'train_model', 'manual__2024-10-24T20:45:11.903795+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/HW2.py', '--cfg-path', '/tmp/tmp2krlwzyk']
[2024-10-24T20:45:44.341+0000] {standard_task_runner.py:91} INFO - Job 188: Subtask train_model
[2024-10-24T20:45:44.406+0000] {task_command.py:426} INFO - Running <TaskInstance: lapshin_nikita_linear_regression.train_model manual__2024-10-24T20:45:11.903795+00:00 [running]> on host 701639cb5e9f
[2024-10-24T20:45:44.504+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Elizaveta Gavrilova' AIRFLOW_CTX_DAG_ID='lapshin_nikita_linear_regression' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T20:45:11.903795+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-24T20:45:11.903795+00:00'
[2024-10-24T20:45:44.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-24T20:45:44.541+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-3 with path datasets/prepared_data.csv
[2024-10-24T20:45:44.547+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-24T20:45:44.548+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-24T20:45:49.970+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:45:49 INFO mlflow.tracking.fluent: Experiment with name 'Elizaveta_Gavrilova_linear_regression' does not exist. Creating a new experiment.
[2024-10-24T20:45:50.181+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:45:50 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-24T20:45:55.291+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-10-24T20:45:56.197+0000] {configprovider.py:957} INFO - Found endpoint for s3 via: environment_global.
[2024-10-24T20:46:04.491+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:46:04 INFO mlflow.models.evaluation.default_evaluator: Computing model predictions.
[2024-10-24T20:46:04.516+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/metrics/_regression.py:492 FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
[2024-10-24T20:46:04.519+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:46:04 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...
[2024-10-24T20:46:04.521+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:46:04 WARNING mlflow.models.evaluation.default_evaluator: SHAP or matplotlib package is not installed, so model explainability insights will not be logged.
[2024-10-24T20:46:06.172+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:46:06 INFO mlflow.tracking._tracking_service.client: üèÉ View run linear_regression_run at: http://mlflow-service:5000/#/experiments/405041356203365926/runs/f6052577a68d471fa9c9588db78f29a6.
[2024-10-24T20:46:06.174+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:46:06 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/405041356203365926.
[2024-10-24T20:46:06.193+0000] {python.py:237} INFO - Done. Returned value was: {'model_score': 0.8912486221145098}
[2024-10-24T20:46:06.194+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-24T20:46:06.331+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=lapshin_nikita_linear_regression, task_id=train_model, run_id=manual__2024-10-24T20:45:11.903795+00:00, execution_date=20241024T204511, start_date=20241024T204544, end_date=20241024T204606
[2024-10-24T20:46:06.428+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-24T20:46:06.504+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-24T20:46:06.506+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
