[2024-10-24T20:50:32.808+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-24T20:50:32.821+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lapshin_nikita_linear_regression.train_model manual__2024-10-24T20:49:41.266972+00:00 [queued]>
[2024-10-24T20:50:32.832+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lapshin_nikita_linear_regression.train_model manual__2024-10-24T20:49:41.266972+00:00 [queued]>
[2024-10-24T20:50:32.832+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-10-24T20:50:32.849+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-10-24 20:49:41.266972+00:00
[2024-10-24T20:50:32.901+0000] {standard_task_runner.py:64} INFO - Started process 2575 to run task
[2024-10-24T20:50:32.907+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'lapshin_nikita_linear_regression', 'train_model', 'manual__2024-10-24T20:49:41.266972+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/HW2.py', '--cfg-path', '/tmp/tmpypno37tm']
[2024-10-24T20:50:32.912+0000] {standard_task_runner.py:91} INFO - Job 202: Subtask train_model
[2024-10-24T20:50:32.987+0000] {task_command.py:426} INFO - Running <TaskInstance: lapshin_nikita_linear_regression.train_model manual__2024-10-24T20:49:41.266972+00:00 [running]> on host 701639cb5e9f
[2024-10-24T20:50:33.078+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nikita Lapshin' AIRFLOW_CTX_DAG_ID='lapshin_nikita_linear_regression' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T20:49:41.266972+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-24T20:49:41.266972+00:00'
[2024-10-24T20:50:33.079+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-24T20:50:33.115+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-3 with path datasets/prepared_data.csv
[2024-10-24T20:50:33.122+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-24T20:50:33.123+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-24T20:50:47.267+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:50:47 INFO mlflow.tracking.fluent: Experiment with name 'Nikita_Lapshin' does not exist. Creating a new experiment.
[2024-10-24T20:50:48.202+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:50:48 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-24T20:51:11.686+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-10-24T20:51:20.464+0000] {configprovider.py:957} INFO - Found endpoint for s3 via: environment_global.
[2024-10-24T20:51:29.652+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:51:29 INFO mlflow.models.evaluation.default_evaluator: Computing model predictions.
[2024-10-24T20:51:29.695+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/metrics/_regression.py:492 FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
[2024-10-24T20:51:29.708+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:51:29 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...
[2024-10-24T20:51:29.718+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:51:29 WARNING mlflow.models.evaluation.default_evaluator: SHAP or matplotlib package is not installed, so model explainability insights will not be logged.
[2024-10-24T20:51:32.839+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:51:32 INFO mlflow.tracking._tracking_service.client: üèÉ View run linear_regression_run at: http://mlflow-service:5000/#/experiments/574506882779760145/runs/5cc31ee647704fa8a70748b7ea2d5793.
[2024-10-24T20:51:34.047+0000] {logging_mixin.py:188} WARNING - 2024/10/24 20:51:34 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/574506882779760145.
[2024-10-24T20:51:34.470+0000] {python.py:237} INFO - Done. Returned value was: {'model_score': 0.8912486221145098}
[2024-10-24T20:51:35.642+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-24T20:51:38.765+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=lapshin_nikita_linear_regression, task_id=train_model, run_id=manual__2024-10-24T20:49:41.266972+00:00, execution_date=20241024T204941, start_date=20241024T205032, end_date=20241024T205138
[2024-10-24T20:51:39.856+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-24T20:51:40.188+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-24T20:51:40.195+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
